sudo: required

services:
  - docker

language: go

go:
  - "1.22"

env:
  - DEP_VERSION="1.45.0"

install:
  # Download and install dep
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

script:
  - make test
